### ISSUE TITLE
WebID-TLS authentication failed

### ISSUE THREAD

**Issue by almereyda** [linkeddata/contacts#13]
Using a quite recent account from https://almereyda.databox.me, I couldn't login to the live instance of this application at github.io.

**Comment by almereyda** [comment]
Well, the error message could be a bit more expressive. Of course I am using another browser than the one with which I created said LDP store.

Making these identities transient between devices may be a challenge - or solved by WebID-RSA. Don't know.

**Comment by dmitrizagidulin** [comment]
@almereyda - Agreed, we're definitely aware of the usability nightmare of trying to access one's account from different browsers. We're currently working on alternative authentication mechanisms to help with this.
